-- Create table for storing student exclusions from examinations
CREATE TABLE IF NOT EXISTS public.exam_exclusions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id integer REFERENCES public.examinations(id) ON DELETE CASCADE NOT NULL,
    student_id integer REFERENCES public.students(id) ON DELETE CASCADE NOT NULL,
    school_id integer NOT NULL, -- using integer as requested
    reason text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(exam_id, student_id)
);

-- Disable Row Level Security to match the project's security model (referencing existing schema patterns)
ALTER TABLE public.exam_exclusions DISABLE ROW LEVEL SECURITY;

-- Grant access to authenticated users
GRANT ALL ON public.exam_exclusions TO authenticated;
