// Release notes content - auto-generated from RELEASE_NOTES.md
// Run: npm run sync-release-notes (or node scripts/sync-release-notes.js)
// DO NOT EDIT THIS FILE MANUALLY - it will be overwritten

export const getReleaseNotes = (): string => {
  return `# ***What's New!***

## New **Notification System**
- Added New Notification System for both Staff and Students.`;
};
