// Release notes content - auto-generated from RELEASE_NOTES.md
// Run: npm run sync-release-notes (or node scripts/sync-release-notes.js)
// DO NOT EDIT THIS FILE MANUALLY - it will be overwritten

export const getReleaseNotes = (): string => {
  return `# ***What's New!***

## 🔒 اہم اعلان (Important Announcement)

**معزز صارفین،**

ہم آپ کو یہ اطلاع دینا چاہتے ہیں کہ ہماری ایپ کی **سیکیورٹی میں نمایاں بہتری** لائی گئی ہے۔ اس کے ساتھ ساتھ **نئی خصوصیات اور بہتریوں** کا اضافہ بھی کیا گیا ہے تاکہ آپ کا تجربہ مزید بہتر ہو سکے۔

**براہ کرم اپنی ایپ کو اپ ڈیٹ کریں** تاکہ آپ تازہ ترین سیکیورٹی اپ ڈیٹس اور نئی خصوصیات سے فائدہ اٹھا سکیں۔

---

**Dear Users,**

We are pleased to inform you that the **security of our application has been significantly enhanced**. Additionally, **new features and improvements** have been added to provide you with a better experience.

**Please make sure to update your app** to benefit from the latest security updates and new features.

---`;
};
