-- Create table for storing device push tokens
CREATE TABLE IF NOT EXISTS public.device_push_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    school_id BIGINT NOT NULL,
    platform TEXT NOT NULL CHECK (platform IN ('electron', 'android', 'ios', 'web')),
    token TEXT NOT NULL,
    last_seen_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, token)
);

-- Add RLS policies
ALTER TABLE public.device_push_tokens ENABLE ROW LEVEL SECURITY;

-- Allow users to insert/update their own tokens
CREATE POLICY "Users can manage device tokens" 
    ON public.device_push_tokens 
    FOR ALL 
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Create function to update last_seen_at on conflict
CREATE OR REPLACE FUNCTION public.upsert_device_token(
    p_user_id BIGINT,
    p_school_id BIGINT,
    p_platform TEXT,
    p_token TEXT
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    INSERT INTO public.device_push_tokens (user_id, school_id, platform, token, last_seen_at)
    VALUES (p_user_id, p_school_id, p_platform, p_token, NOW())
    ON CONFLICT (user_id, token) 
    DO UPDATE SET last_seen_at = NOW(), school_id = p_school_id;
END;
$$;
